# Finance API 설정
finance:
  api:
    base-url: https://finopenapi.ssafy.io/ssafy/api/v1/edu
    timeout: 10
    key: ${FINANCE_API_KEY:}

# JWT 인증 설정
jwt:
  secret-key: ${JWT_SECRET_KEY:9ed4f9db32dc65abbbd68d960d467cdeb57f6aa920bbd790eec1b9fec5b4d5bc}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:900000}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}

# 기존 설정들...
spring:
  application:
    name: solsol
  profiles:
    active: local
    
# 로컬 개발 환경
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# 개발 환경
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/solsol_dev
    username: ${DB_USER:solsol}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

# 운영 환경
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:solsol}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

# 로깅 설정
logging:
  level:
    com.solsolhey: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"