spring:
  application:
    name: solsol

  # 프로파일별 설정
  profiles:
    active: local

  # 데이터베이스 설정
  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.H2Dialect}
        format_sql: true
        use_sql_comments: true

  # H2 Console (로컬 개발용)
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}
      path: /h2-console

  # Flyway 설정
  flyway:
    enabled: ${FLYWAY_ENABLED:false}
    baseline-on-migrate: true
    locations: classpath:db/migration

# 서버 설정
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

# JWT 설정
jwt:
  secret-key: ${JWT_SECRET_KEY:mySecretKeyForSolsolHeyHackathon2024VeryLongSecretKey}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000} # 1시간
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000} # 7일

# 신한 API 설정
shinhan:
  api:
    base-url: ${SHINHAN_API_BASE_URL:https://finopenapi.ssafy.io/ssafy/api/v1}
    user-key: ${SHINHAN_API_USER_KEY:}
    
# 로깅 설정
logging:
  level:
    com.solsolhey.solsol: ${LOG_LEVEL:DEBUG}
    org.springframework.security: ${SECURITY_LOG_LEVEL:DEBUG}
    org.hibernate.SQL: ${SQL_LOG_LEVEL:DEBUG}
    org.hibernate.type.descriptor.sql.BasicBinder: ${SQL_BIND_LOG_LEVEL:TRACE}

---
# 로컬 개발 환경
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  flyway:
    enabled: false

---
# 개발 환경 (PostgreSQL)
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/solsolhey_dev
    username: solsol_user
    password: solsol_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: false
  flyway:
    enabled: true

---
# 운영 환경
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: false
  flyway:
    enabled: true

logging:
  level:
    com.solsolhey.solsol: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
