-- Create friend_interactions table to support friend activity notifications
CREATE TABLE IF NOT EXISTS friend_interactions (
    interaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_user_id   BIGINT       NOT NULL,
    to_user_id     BIGINT       NOT NULL,
    interaction_type VARCHAR(50) NOT NULL,
    message        VARCHAR(200),
    is_read        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Foreign keys
ALTER TABLE friend_interactions
    ADD CONSTRAINT fk_friend_interactions_from_user
        FOREIGN KEY (from_user_id) REFERENCES users(user_id);

ALTER TABLE friend_interactions
    ADD CONSTRAINT fk_friend_interactions_to_user
        FOREIGN KEY (to_user_id) REFERENCES users(user_id);

-- Helpful indexes for common queries
CREATE INDEX IF NOT EXISTS idx_friend_interactions_to_user
    ON friend_interactions (to_user_id);

CREATE INDEX IF NOT EXISTS idx_friend_interactions_created_at
    ON friend_interactions (created_at);

