-- Create mascots and mascot_snapshots tables (H2/PostgreSQL compatible)

-- Mascots: one per user (unique), stores customization and progression
CREATE TABLE IF NOT EXISTS mascots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    type VARCHAR(20) NOT NULL,
    equipped_item VARCHAR(100),
    equipped_layout TEXT,
    snapshot_image TEXT,
    background_id VARCHAR(50) DEFAULT 'bg_room_basic',
    background_color VARCHAR(7),
    background_pattern VARCHAR(20),
    exp INT NOT NULL DEFAULT 0,
    level INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_mascots_user UNIQUE (user_id),
    CONSTRAINT fk_mascots_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_mascots_user_id ON mascots(user_id);

-- Mascot snapshots: stores generated/ uploaded snapshot images per user/mascot
CREATE TABLE IF NOT EXISTS mascot_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    mascot_id BIGINT NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mascot_snapshots_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_mascot_snapshots_mascot FOREIGN KEY (mascot_id) REFERENCES mascots(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_mascot_snapshots_user_id ON mascot_snapshots(user_id);
CREATE INDEX IF NOT EXISTS idx_mascot_snapshots_mascot_id ON mascot_snapshots(mascot_id);

