CREATE TABLE IF NOT EXISTS friend_like_pair_state (
    state_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_low_id BIGINT NOT NULL,
    user_high_id BIGINT NOT NULL,
    last_sender_id BIGINT,
    CONSTRAINT uk_like_pair_low_high UNIQUE (user_low_id, user_high_id),
    CONSTRAINT fk_like_pair_low FOREIGN KEY (user_low_id) REFERENCES users(user_id),
    CONSTRAINT fk_like_pair_high FOREIGN KEY (user_high_id) REFERENCES users(user_id),
    CONSTRAINT fk_like_pair_last FOREIGN KEY (last_sender_id) REFERENCES users(user_id)
);

CREATE INDEX IF NOT EXISTS idx_like_pair_low_high ON friend_like_pair_state(user_low_id, user_high_id);

