-- Daily like limit counter per (from_user, to_user, date)
CREATE TABLE IF NOT EXISTS friend_like_daily_counter (
    counter_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_user_id BIGINT NOT NULL,
    to_user_id BIGINT NOT NULL,
    like_date DATE NOT NULL,
    like_count INT NOT NULL DEFAULT 0,
    CONSTRAINT uk_like_counter_from_to_date UNIQUE (from_user_id, to_user_id, like_date),
    CONSTRAINT fk_like_counter_from FOREIGN KEY (from_user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_like_counter_to FOREIGN KEY (to_user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_like_counter_from ON friend_like_daily_counter(from_user_id);
CREATE INDEX IF NOT EXISTS ix_like_counter_to ON friend_like_daily_counter(to_user_id);
CREATE INDEX IF NOT EXISTS ix_like_counter_date ON friend_like_daily_counter(like_date);

